### ISSUE TITLE
Custom URI validation

### ISSUE THREAD

**Issue by mhemeryck** [snok/drf-openapi-tester#244]
Hi, thanks for this great library since it helps us to validate our spec against our API!

We have an API that passes google cloud store links around as part of the request / responses.

In our (YAML, openapi) spec, we document those e.g. as

```yaml
      documentUri:                                                                                                                                                                        
        type: string                                                                                                                                                                         
        format: uri                                                                                                                                                                          
        description: remote reference to get the file                                                                                                                                    
        example: 'gs://bucket/obj.pdf'  
```

However, the built-in validation seems to rely on django's URL validators:
https://github.com/snok/drf-openapi-tester/blob/6ab4530347c652cae0e72371946138fb81ae453a/openapi_tester/validators.py#L67-L68

which in turn only support more commonly known URL schemes: https://docs.djangoproject.com/en/3.2/ref/validators/

I've also looked into adding a custom validator with the `validators` kwarg, but it looks like custom validators are run in addition to the base set of validators, not in place of.

What would be the best way to add such custom URI scheme? Would be happy to drop a PR once it's clear what to do.
